### ISSUE TITLE
Question: How to upload photo in React native using Axios ?

### ISSUE THREAD

**Issue by kaiyes** [benawad/gello-world#1]
Hi, Nice Tutorial.  I used cloudinary before in other meteor apps so was kinda familiar with that. Thanks for the Tutorial. 

Now, I was following this to get things up and running in React native. I am using https://github.com/ivpusic/react-native-image-crop-picker to pick the image. Image picks up fine. gallery shows ok,  I can console.log the result and i see data and uri of image and image updates but  problem is  I can't seem to upload it to cloudinary.

Here is my code for uploading the photo
```
  _onPhotoPress = () => {
    ImagePicker.openPicker({
      width: 300,
      height: 400,
      cropping: true,
      mediaType: 'photo'
    })
      .then(image => {
        this.setState({ pic: image.sourceURL, file: image })
        console.log(this.state)
        console.log(image)
        const formData = new FormData()
        formData.append('file', this.state.file)
        formData.append('upload_preset', 'XXXX')
        return axios.post(
          `https://api.cloudinary.com/v1_1/XXX`,
          formData
        )
      })
      .catch(err => {
        console.log(`${err}`)
      })
  }
```

And here is the image object. 
![screenshot 2017-09-13 09 22 55](https://user-images.githubusercontent.com/5293742/30358254-339a75b2-9865-11e7-8712-079a9f7c8f93.png)

This is the error : 
![screenshot 2017-09-13 13 27 15](https://user-images.githubusercontent.com/5293742/30364770-65090362-9887-11e7-9120-c25787b6b6dc.png)

Thanks in Advance. Creating a react native-cloudinary-GQL image upload tutorial would be nice.

**Comment by benawad** [comment]
We need to figure out why there's a network error. Try doing
console.log(err) to see if you get a better error message. If not, go to
the network tab and look at the failed request it should have a response
from cloudinary saying what's missing.

Your code looks good, I would guess it has to do with your upload preset.

**Comment by kaiyes** [comment]
Thanks for getting back to me. I was looking around for react native photo and file upload solution. Looks like firebase is the most painless solution. I used cloudinary with meteor for two years. I was wondering how come we don't need `api_secret` and `api_key` but oh well.

**Comment by benawad** [comment]
I've heard firebase is really good, so that should work well for you. We
were doing unsigned requests which don't need any API keys. If you do a
signed request you will need those.

**Comment by mayankzen1** [comment]
Use JSON.parse(JSON.stringify(err)); to get better view for error message.

**Comment by ue** [comment]
use image instead of `this.state.file` it not set to the local state already in this case set state not working async
